In [3]:
import numpy as np
import pandas as pd


df = pd.read_csv(r"C:\Users\hp\Desktop\Jupyter_note_books_data_science\customer_churn_dataset.csv", encoding='latin1')


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   CustomerID        30000 non-null  int64  
 1   Gender            30000 non-null  object 
 2   Age               30000 non-null  int64  
 3   Tenure            30000 non-null  int64  
 4   SubscriptionType  30000 non-null  object 
 5   MonthlyCharges    30000 non-null  float64
 6   TotalCharges      30000 non-null  float64
 7   InternetUsageGB   30000 non-null  float64
 8   CallsPerMonth     30000 non-null  int64  
 9   Complaints        30000 non-null  int64  
 10  PaymentMethod     30000 non-null  object 
 11  ContractType      30000 non-null  object 
 12  HasDependents     30000 non-null  object 
 13  Churn             30000 non-null  object 
dtypes: float64(3), int64(5), object(6)
memory usage: 3.2+ MB


In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['SubscriptionType']=le.fit_transform(df['SubscriptionType'])
df['PaymentMethod']=le.fit_transform(df['PaymentMethod'])
df['ContractType']=le.fit_transform(df['ContractType'])
df['HasDependents']=le.fit_transform(df['HasDependents'])
df['Churn']=le.fit_transform(df['Churn'])




In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   CustomerID        30000 non-null  int64  
 1   Gender            30000 non-null  int64  
 2   Age               30000 non-null  int64  
 3   Tenure            30000 non-null  int64  
 4   SubscriptionType  30000 non-null  int64  
 5   MonthlyCharges    30000 non-null  float64
 6   TotalCharges      30000 non-null  float64
 7   InternetUsageGB   30000 non-null  float64
 8   CallsPerMonth     30000 non-null  int64  
 9   Complaints        30000 non-null  int64  
 10  PaymentMethod     30000 non-null  int64  
 11  ContractType      30000 non-null  int64  
 12  HasDependents     30000 non-null  int64  
 13  Churn             30000 non-null  int64  
dtypes: float64(3), int64(11)
memory usage: 3.2 MB


In [7]:
df.head()

CustomerID  Gender  Age  Tenure  SubscriptionType  MonthlyCharges  \
0       10001       1   45      32                 0           46.90   
1       10002       0   39       3                 2           45.25   
2       10003       1   62      22                 1          125.47   
3       10004       1   33      68                 2           93.29   
4       10005       1   30      52                 2           73.81   

   TotalCharges  InternetUsageGB  CallsPerMonth  Complaints  PaymentMethod  \
0       1563.99            38.28             27           1              2   
1        121.78           196.96             30           1              3   
2       2759.91            66.05             72           1              0   
3       6422.70            35.04            124           0              1   
4       3756.45           194.89             90           0              0   

   ContractType  HasDependents  Churn  
0             0              0      1  
1             0              0      1  
2             0              0      1  
3             0              1      0  
4             0              0      0

In [8]:
x = df.drop(columns=['Churn'])
y = df['Churn']

In [9]:
from sklearn.model_selection import train_test_split as tts

x_train,x_test,y_train,y_test = tts(x,y, test_size= 0.3, random_state= 47)

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [11]:

Random_model = RandomForestClassifier()
Random_model.fit(x_train, y_train)

RandomForestClassifier()

In [12]:
Logistic_Model = LogisticRegression()
Logistic_Model.fit(x_train, y_train)


c:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
decision_model = DecisionTreeClassifier()
decision_model.fit(x_train, y_train)


DecisionTreeClassifier()

In [14]:
KN_model = KNeighborsClassifier()
KN_model.fit(x_train, y_train)

KNeighborsClassifier()

In [15]:
Logistic_predictions = Logistic_Model.predict(x_test)
Logistic_predictions

array([0, 0, 1, ..., 0, 0, 1])

In [16]:
decision_predictions = decision_model.predict(x_test)
decision_predictions

array([0, 0, 0, ..., 0, 0, 0])

In [17]:
KN_predictions = KN_model.predict(x_test)
KN_predictions

array([0, 0, 1, ..., 0, 0, 1])

In [18]:
Random_predictions = Random_model.predict(x_test)
Random_predictions

array([0, 1, 1, ..., 0, 0, 0])

In [19]:
from sklearn.metrics import accuracy_score,r2_score,precision_score
# Accuracy Score
logistic_regression_accuracy_score = accuracy_score(y_test, Logistic_predictions)
decision_tree_classifier_accuracy_score = accuracy_score(y_test, decision_predictions)
KN_model_accuracy_score = accuracy_score(y_test, KN_predictions)
Random_model_accuracy_score = accuracy_score(y_test, Random_predictions)
# R2 Score
logistic_regression_R2_score = r2_score(y_test, Logistic_predictions)
decision_tree_classifier_R2_score = r2_score(y_test, decision_predictions)
KN_model_R2_score = r2_score(y_test, KN_predictions)
Random_model_R2_score = r2_score(y_test, Random_predictions)
# Precision Score
logistic_regression_Precision_score = precision_score(y_test, Logistic_predictions)
decision_tree_classifier_Precision_score = precision_score(y_test, decision_predictions)
KN_model_Precision_score = precision_score(y_test, KN_predictions)
Random_model_Precision_score = precision_score(y_test, Random_predictions)
# Printing
print("Accuracy_score   R2_score    Precision_score")
print("Logistic Regression: ", logistic_regression_accuracy_score, logistic_regression_R2_score,logistic_regression_Precision_score)
print("Decision Tree Classifier : ", decision_tree_classifier_accuracy_score, decision_tree_classifier_R2_score,decision_tree_classifier_Precision_score)
print("KN model  : ", KN_model_accuracy_score, KN_model_R2_score, KN_model_Precision_score)
print("Random Forest Model: ", Random_model_accuracy_score,Random_model_R2_score, Random_model_Precision_score)




Accuracy_score   R2_score    Precision_score
Logistic Regression:  0.6238888888888889 -0.5768058969279795 0.5665198237885463
Decision Tree Classifier :  0.629 -0.5553781063050289 0.5275062831611281
KN model  :  0.5672222222222222 -0.8143748799215598 0.4374346462181945
Random Forest Model:  0.7047777777777777 -0.2376878192430254 0.6428339291517712


In [20]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight='balanced',
    random_state=42
)


In [21]:
model.fit(x_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=10,
                       min_samples_leaf=2, min_samples_split=5,
                       n_estimators=200, random_state=42)

In [22]:
y_pred = model.predict(x_test)

In [23]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.77      0.74      0.76      5464
           1       0.63      0.66      0.64      3536

    accuracy                           0.71      9000
   macro avg       0.70      0.70      0.70      9000
weighted avg       0.71      0.71      0.71      9000



In [24]:
import joblib

# Save your trained model
joblib.dump(model, "churn_model.pkl")


# Load it again later
model = joblib.load("churn_model.pkl")


In [25]:
import joblib
# Save your trained model
joblib.dump(Random_model, "churn_Random_model.pkl")

['churn_Random_model.pkl']

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   CustomerID        30000 non-null  int64  
 1   Gender            30000 non-null  int64  
 2   Age               30000 non-null  int64  
 3   Tenure            30000 non-null  int64  
 4   SubscriptionType  30000 non-null  int64  
 5   MonthlyCharges    30000 non-null  float64
 6   TotalCharges      30000 non-null  float64
 7   InternetUsageGB   30000 non-null  float64
 8   CallsPerMonth     30000 non-null  int64  
 9   Complaints        30000 non-null  int64  
 10  PaymentMethod     30000 non-null  int64  
 11  ContractType      30000 non-null  int64  
 12  HasDependents     30000 non-null  int64  
 13  Churn             30000 non-null  int64  
dtypes: float64(3), int64(11)
memory usage: 3.2 MB
